In [2]:
import pandas as pd

df = pd.read_csv("./titanic.csv")
df = df.set_index("Name")
df

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Name,,,,,,,,,,,
"Braund, Mr. Owen Harris",1,0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
"Heikkinen, Miss. Laina",3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
"Futrelle, Mrs. Jacques Heath (Lily May Peel)",4,1,1,female,35.0,1,0,113803,53.1000,C123,S
"Allen, Mr. William Henry",5,0,3,male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
"Montvila, Rev. Juozas",887,0,2,male,27.0,0,0,211536,13.0000,NaN,S
"Graham, Miss. Margaret Edith",888,1,1,female,19.0,0,0,112053,30.0000,B42,S
"Johnston, Miss. Catherine Helen ""Carrie""",889,0,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S
"Behr, Mr. Karl Howell",890,1,1,male,26.0,0,0,111369,30.0000,C148,C
"Dooley, Mr. Patrick",891,0,3,male,32.0,0,0,370376,7.7500,NaN,Q

In [10]:
df.sort_index()

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Name,,,,,,,,,,,
"Abbing, Mr. Anthony",846,0,3,male,42.0,0,0,C.A. 5547,7.5500,NaN,S
"Abbott, Mr. Rossmore Edward",747,0,3,male,16.0,1,1,C.A. 2673,20.2500,NaN,S
"Abbott, Mrs. Stanton (Rosa Hunt)",280,1,3,female,35.0,1,1,C.A. 2673,20.2500,NaN,S
"Abelson, Mr. Samuel",309,0,2,male,30.0,1,0,P/PP 3381,24.0000,NaN,C
"Abelson, Mrs. Samuel (Hannah Wizosky)",875,1,2,female,28.0,1,0,P/PP 3381,24.0000,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...
"de Mulder, Mr. Theodore",287,1,3,male,30.0,0,0,345774,9.5000,NaN,S
"de Pelsmaeker, Mr. Alfons",283,0,3,male,16.0,0,0,345778,9.5000,NaN,S
"del Carlo, Mr. Sebastiano",362,0,2,male,29.0,1,0,SC/PARIS 2167,27.7208,NaN,C
"van Billiard, Mr. Austin Blyler",154,0,3,male,40.5,0,2,A/5. 851,14.5000,NaN,S
"van Melkebeke, Mr. Philemon",869,0,3,male,NaN,0,0,345777,9.5000,NaN,S

In [ ]:
df.sort_index(ascending=False                                                                                               )

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Name,,,,,,,,,,,
"van Melkebeke, Mr. Philemon",869,0,3,male,NaN,0,0,345777,9.5000,NaN,S
"van Billiard, Mr. Austin Blyler",154,0,3,male,40.5,0,2,A/5. 851,14.5000,NaN,S
"del Carlo, Mr. Sebastiano",362,0,2,male,29.0,1,0,SC/PARIS 2167,27.7208,NaN,C
"de Pelsmaeker, Mr. Alfons",283,0,3,male,16.0,0,0,345778,9.5000,NaN,S
"de Mulder, Mr. Theodore",287,1,3,male,30.0,0,0,345774,9.5000,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
"Abelson, Mrs. Samuel (Hannah Wizosky)",875,1,2,female,28.0,1,0,P/PP 3381,24.0000,NaN,C
"Abelson, Mr. Samuel",309,0,2,male,30.0,1,0,P/PP 3381,24.0000,NaN,C
"Abbott, Mrs. Stanton (Rosa Hunt)",280,1,3,female,35.0,1,1,C.A. 2673,20.2500,NaN,S
"Abbott, Mr. Rossmore Edward",747,0,3,male,16.0,1,1,C.A. 2673,20.2500,NaN,S
"Abbing, Mr. Anthony",846,0,3,male,42.0,0,0,C.A. 5547,7.5500,NaN,S

In [14]:
df.index

Index(['Braund, Mr. Owen Harris',
       'Cumings, Mrs. John Bradley (Florence Briggs Thayer)',
       'Heikkinen, Miss. Laina',
       'Futrelle, Mrs. Jacques Heath (Lily May Peel)',
       'Allen, Mr. William Henry', 'Moran, Mr. James',
       'McCarthy, Mr. Timothy J', 'Palsson, Master. Gosta Leonard',
       'Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)',
       'Nasser, Mrs. Nicholas (Adele Achem)',
       ...
       'Markun, Mr. Johann', 'Dahlberg, Miss. Gerda Ulrika',
       'Banfield, Mr. Frederick James', 'Sutehall, Mr. Henry Jr',
       'Rice, Mrs. William (Margaret Norton)', 'Montvila, Rev. Juozas',
       'Graham, Miss. Margaret Edith',
       'Johnston, Miss. Catherine Helen "Carrie"', 'Behr, Mr. Karl Howell',
       'Dooley, Mr. Patrick'],
      dtype='object', name='Name', length=891)

In [16]:
for n in df.index:
    print(n)

Braund, Mr. Owen Harris
Cumings, Mrs. John Bradley (Florence Briggs Thayer)
Heikkinen, Miss. Laina
Futrelle, Mrs. Jacques Heath (Lily May Peel)
Allen, Mr. William Henry
Moran, Mr. James
McCarthy, Mr. Timothy J
Palsson, Master. Gosta Leonard
Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
Nasser, Mrs. Nicholas (Adele Achem)
Sandstrom, Miss. Marguerite Rut
Bonnell, Miss. Elizabeth
Saundercock, Mr. William Henry
Andersson, Mr. Anders Johan
Vestrom, Miss. Hulda Amanda Adolfina
Hewlett, Mrs. (Mary D Kingcome)
Rice, Master. Eugene
Williams, Mr. Charles Eugene
Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)
Masselmani, Mrs. Fatima
Fynney, Mr. Joseph J
Beesley, Mr. Lawrence
McGowan, Miss. Anna "Annie"
Sloper, Mr. William Thompson
Palsson, Miss. Torborg Danira
Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)
Emir, Mr. Farred Chehab
Fortune, Mr. Charles Alexander
O'Dwyer, Miss. Ellen "Nellie"
Todoroff, Mr. Lalio
Uruchurtu, Don. Manuel E
Spencer, Mrs. William Augustus (Marie Eugenie)
Glynn, Miss. Mary Agatha
Wheadon, Mr. Edward H
Meyer, Mr. Edgar Joseph
Holverson, Mr. Alexander Oskar
Mamee, Mr. Hanna
Cann, Mr. Ernest Charles
Vander Planke, Miss. Augusta Maria
Nicola-Yarred, Miss. Jamila
Ahlin, Mrs. Johan (Johanna Persdotter Larsson)
Turpin, Mrs. William John Robert (Dorothy Ann Wonnacott)
Kraeff, Mr. Theodor
Laroche, Miss. Simonne Marie Anne Andree
Devaney, Miss. Margaret Delia
Rogers, Mr. William John
Lennon, Mr. Denis
O'Driscoll, Miss. Bridget
Samaan, Mr. Youssef
Arnold-Franchi, Mrs. Josef (Josefine Franchi)
Panula, Master. Juha Niilo
Nosworthy, Mr. Richard Cater
Harper, Mrs. Henry Sleeper (Myna Haxtun)
Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkinson)
Ostby, Mr. Engelhart Cornelius
Woolner, Mr. Hugh
Rugg, Miss. Emily
Novel, Mr. Mansouer
West, Miss. Constance Mirium
Goodwin, Master. William Frederick
Sirayanian, Mr. Orsen
Icard, Miss. Amelie
Harris, Mr. Henry Birkhardt
Skoog, Master. Harald
Stewart, Mr. Albert A
Moubarek, Master. Gerios
Nye, Mrs. (Elizabeth Ramell)
Crease, Mr. Ernest James
Andersson, Miss. Erna Alexandra
Kink, Mr. Vincenz
Jenkin, Mr. Stephen Curnow
Goodwin, Miss. Lillian Amy
Hood, Mr. Ambrose Jr
Chronopoulos, Mr. Apostolos
Bing, Mr. Lee
Moen, Mr. Sigurd Hansen
Staneff, Mr. Ivan
Moutal, Mr. Rahamin Haim
Caldwell, Master. Alden Gates
Dowdell, Miss. Elizabeth
Waelens, Mr. Achille
Sheerlinck, Mr. Jan Baptist
McDermott, Miss. Brigdet Delia
Carrau, Mr. Francisco M
Ilett, Miss. Bertha
Backstrom, Mrs. Karl Alfred (Maria Mathilda Gustafsson)
Ford, Mr. William Neal
Slocovski, Mr. Selman Francis
Fortune, Miss. Mabel Helen
Celotti, Mr. Francesco
Christmann, Mr. Emil
Andreasson, Mr. Paul Edvin
Chaffee, Mr. Herbert Fuller
Dean, Mr. Bertram Frank
Coxon, Mr. Daniel
Shorney, Mr. Charles Joseph
Goldschmidt, Mr. George B
Greenfield, Mr. William Bertram
Doling, Mrs. John T (Ada Julia Bone)
Kantor, Mr. Sinai
Petranec, Miss. Matilda
Petroff, Mr. Pastcho ("Pentcho")
White, Mr. Richard Frasar
Johansson, Mr. Gustaf Joel
Gustafsson, Mr. Anders Vilhelm
Mionoff, Mr. Stoytcho
Salkjelsvik, Miss. Anna Kristine
Moss, Mr. Albert Johan
Rekic, Mr. Tido
Moran, Miss. Bertha
Porter, Mr. Walter Chamberlain
Zabour, Miss. Hileni
Barton, Mr. David John
Jussila, Miss. Katriina
Attalah, Miss. Malake
Pekoniemi, Mr. Edvard
Connors, Mr. Patrick
Turpin, Mr. William John Robert
Baxter, Mr. Quigg Edmond
Andersson, Miss. Ellis Anna Maria
Hickman, Mr. Stanley George
Moore, Mr. Leonard Charles
Nasser, Mr. Nicholas
Webber, Miss. Susan
White, Mr. Percival Wayland
Nicola-Yarred, Master. Elias
McMahon, Mr. Martin
Madsen, Mr. Fridtjof Arne
Peter, Miss. Anna
Ekstrom, Mr. Johan
Drazenoic, Mr. Jozef
Coelho, Mr. Domingos Fernandeo
Robins, Mrs. Alexander A (Grace Charity Laury)
Weisz, Mrs. Leopold (Mathilde Francoise Pede)
Sobey, Mr. Samuel James Hayden
Richard, Mr. Emile
Newsom, Miss. Helen Monypeny
Futrelle, Mr. Jacques Heath
Osen, Mr. Olaf Elon
Giglio, Mr. Victor
Boulos, Mrs. Joseph (Sultana)
Nysten, Miss. Anna Sofia
Hakkarainen, Mrs. Pekka Pietari (Elin Matilda Dolck)
Burke, Mr. Jeremiah
Andrew, Mr. Edgardo Samuel
Nicholls, Mr. Joseph Charles
Andersson, Mr. August Edvard ("Wennerstrom")
Ford, Miss. Robina Maggie "Ruby"
Navratil, Mr. Michel ("Louis M Hoffman")
Byles, Rev. Thomas Roussel Davids
Bateman, Rev. Robert James
Pears, Mrs. Thomas (Edith Wearne)
Meo, Mr. Alfonzo
van Billiard, Mr. Austin Blyler
Olsen, Mr. Ole Martin
Williams, Mr. Charles Duane
Gilnagh, Miss. Katherine "Katie"
Corn, Mr. Harry
Smiljanic, Mr. Mile
Sage, Master. Thomas Henry
Cribb, Mr. John Hatfield
Watt, Mrs. James (Elizabeth "Bessie" Inglis Milne)
Bengtsson, Mr. John Viktor
Calic, Mr. Jovo
Panula, Master. Eino Viljami
Goldsmith, Master. Frank John William "Frankie"
Chibnall, Mrs. (Edith Martha Bowerman)
Skoog, Mrs. William (Anna Bernhardina Karlsson)
Baumann, Mr. John D
Ling, Mr. Lee
Van der hoef, Mr. Wyckoff
Rice, Master. Arthur
Johnson, Miss. Eleanor Ileen
Sivola, Mr. Antti Wilhelm
Smith, Mr. James Clinch
Klasen, Mr. Klas Albin
Lefebre, Master. Henry Forbes
Isham, Miss. Ann Elizabeth
Hale, Mr. Reginald
Leonard, Mr. Lionel
Sage, Miss. Constance Gladys
Pernot, Mr. Rene
Asplund, Master. Clarence Gustaf Hugo
Becker, Master. Richard F
Kink-Heilmann, Miss. Luise Gretchen
Rood, Mr. Hugh Roscoe
O'Brien, Mrs. Thomas (Johanna "Hannah" Godfrey)
Romaine, Mr. Charles Hallace ("Mr C Rolmane")
Bourke, Mr. John
Turcin, Mr. Stjepan
Pinsky, Mrs. (Rosa)
Carbines, Mr. William
Andersen-Jensen, Miss. Carla Christine Nielsine
Navratil, Master. Michel M
Brown, Mrs. James Joseph (Margaret Tobin)
Lurette, Miss. Elise
Mernagh, Mr. Robert
Olsen, Mr. Karl Siegwart Andreas
Madigan, Miss. Margaret "Maggie"
Yrois, Miss. Henriette ("Mrs Harbeck")
Vande Walle, Mr. Nestor Cyriel
Sage, Mr. Frederick
Johanson, Mr. Jakob Alfred
Youseff, Mr. Gerious
Cohen, Mr. Gurshon "Gus"
Strom, Miss. Telma Matilda
Backstrom, Mr. Karl Alfred
Albimona, Mr. Nassef Cassem
Carr, Miss. Helen "Ellen"
Blank, Mr. Henry
Ali, Mr. Ahmed
Cameron, Miss. Clear Annie
Perkin, Mr. John Henry
Givard, Mr. Hans Kristensen
Kiernan, Mr. Philip
Newell, Miss. Madeleine
Honkanen, Miss. Eliina
Jacobsohn, Mr. Sidney Samuel
Bazzani, Miss. Albina
Harris, Mr. Walter
Sunderland, Mr. Victor Francis
Bracken, Mr. James H
Green, Mr. George Henry
Nenkoff, Mr. Christo
Hoyt, Mr. Frederick Maxfield
Berglund, Mr. Karl Ivar Sven
Mellors, Mr. William John
Lovell, Mr. John Hall ("Henry")
Fahlstrom, Mr. Arne Jonas
Lefebre, Miss. Mathilde
Harris, Mrs. Henry Birkhardt (Irene Wallach)
Larsson, Mr. Bengt Edvin
Sjostedt, Mr. Ernst Adolf
Asplund, Miss. Lillian Gertrud
Leyson, Mr. Robert William Norman
Harknett, Miss. Alice Phoebe
Hold, Mr. Stephen
Collyer, Miss. Marjorie "Lottie"
Pengelly, Mr. Frederick William
Hunt, Mr. George Henry
Zabour, Miss. Thamine
Murphy, Miss. Katherine "Kate"
Coleridge, Mr. Reginald Charles
Maenpaa, Mr. Matti Alexanteri
Attalah, Mr. Sleiman
Minahan, Dr. William Edward
Lindahl, Miss. Agda Thorilda Viktoria
Hamalainen, Mrs. William (Anna)
Beckwith, Mr. Richard Leonard
Carter, Rev. Ernest Courtenay
Reed, Mr. James George
Strom, Mrs. Wilhelm (Elna Matilda Persson)
Stead, Mr. William Thomas
Lobb, Mr. William Arthur
Rosblom, Mrs. Viktor (Helena Wilhelmina)
Touma, Mrs. Darwis (Hanne Youssef Razi)
Thorne, Mrs. Gertrude Maybelle
Cherry, Miss. Gladys
Ward, Miss. Anna
Parrish, Mrs. (Lutie Davis)
Smith, Mr. Thomas
Asplund, Master. Edvin Rojj Felix
Taussig, Mr. Emil
Harrison, Mr. William
Henry, Miss. Delia
Reeves, Mr. David
Panula, Mr. Ernesti Arvid
Persson, Mr. Ernst Ulrik
Graham, Mrs. William Thompson (Edith Junkins)
Bissette, Miss. Amelia
Cairns, Mr. Alexander
Tornquist, Mr. William Henry
Mellinger, Mrs. (Elizabeth Anne Maidment)
Natsch, Mr. Charles H
Healy, Miss. Hanora "Nora"
Andrews, Miss. Kornelia Theodosia
Lindblom, Miss. Augusta Charlotta
Parkes, Mr. Francis "Frank"
Rice, Master. Eric
Abbott, Mrs. Stanton (Rosa Hunt)
Duane, Mr. Frank
Olsson, Mr. Nils Johan Goransson
de Pelsmaeker, Mr. Alfons
Dorking, Mr. Edward Arthur
Smith, Mr. Richard William
Stankovic, Mr. Ivan
de Mulder, Mr. Theodore
Naidenoff, Mr. Penko
Hosono, Mr. Masabumi
Connolly, Miss. Kate
Barber, Miss. Ellen "Nellie"
Bishop, Mrs. Dickinson H (Helen Walton)
Levy, Mr. Rene Jacques
Haas, Miss. Aloisia
Mineff, Mr. Ivan
Lewy, Mr. Ervin G
Hanna, Mr. Mansour
Allison, Miss. Helen Loraine
Saalfeld, Mr. Adolphe
Baxter, Mrs. James (Helene DeLaudeniere Chaput)
Kelly, Miss. Anna Katherine "Annie Kate"
McCoy, Mr. Bernard
Johnson, Mr. William Cahoone Jr
Keane, Miss. Nora A
Williams, Mr. Howard Hugh "Harry"
Allison, Master. Hudson Trevor
Fleming, Miss. Margaret
Penasco y Castellana, Mrs. Victor de Satode (Maria Josefa Perez de Soto y Vallejo)
Abelson, Mr. Samuel
Francatelli, Miss. Laura Mabel
Hays, Miss. Margaret Bechstein
Ryerson, Miss. Emily Borie
Lahtinen, Mrs. William (Anna Sylfven)
Hendekovic, Mr. Ignjac
Hart, Mr. Benjamin
Nilsson, Miss. Helmina Josefina
Kantor, Mrs. Sinai (Miriam Sternin)
Moraweck, Dr. Ernest
Wick, Miss. Mary Natalie
Spedden, Mrs. Frederic Oakley (Margaretta Corning Stone)
Dennis, Mr. Samuel
Danoff, Mr. Yoto
Slayter, Miss. Hilda Mary
Caldwell, Mrs. Albert Francis (Sylvia Mae Harbaugh)
Sage, Mr. George John Jr
Young, Miss. Marie Grice
Nysveen, Mr. Johan Hansen
Ball, Mrs. (Ada E Hall)
Goldsmith, Mrs. Frank John (Emily Alice Brown)
Hippach, Miss. Jean Gertrude
McCoy, Miss. Agnes
Partner, Mr. Austen
Graham, Mr. George Edward
Vander Planke, Mr. Leo Edmondus
Frauenthal, Mrs. Henry William (Clara Heinsheimer)
Denkoff, Mr. Mitto
Pears, Mr. Thomas Clinton
Burns, Miss. Elizabeth Margaret
Dahl, Mr. Karl Edwart
Blackwell, Mr. Stephen Weart
Navratil, Master. Edmond Roger
Fortune, Miss. Alice Elizabeth
Collander, Mr. Erik Gustaf
Sedgwick, Mr. Charles Frederick Waddington
Fox, Mr. Stanley Hubert
Brown, Miss. Amelia "Mildred"
Smith, Miss. Marion Elsie
Davison, Mrs. Thomas Henry (Mary E Finck)
Coutts, Master. William Loch "William"
Dimic, Mr. Jovan
Odahl, Mr. Nils Martin
Williams-Lambert, Mr. Fletcher Fellows
Elias, Mr. Tannous
Arnold-Franchi, Mr. Josef
Yousif, Mr. Wazli
Vanden Steen, Mr. Leo Peter
Bowerman, Miss. Elsie Edith
Funk, Miss. Annie Clemmer
McGovern, Miss. Mary
Mockler, Miss. Helen Mary "Ellie"
Skoog, Mr. Wilhelm
del Carlo, Mr. Sebastiano
Barbara, Mrs. (Catherine David)
Asim, Mr. Adola
O'Brien, Mr. Thomas
Adahl, Mr. Mauritz Nils Martin
Warren, Mrs. Frank Manley (Anna Sophia Atkinson)
Moussa, Mrs. (Mantoura Boulos)
Jermyn, Miss. Annie
Aubart, Mme. Leontine Pauline
Harder, Mr. George Achilles
Wiklund, Mr. Jakob Alfred
Beavan, Mr. William Thomas
Ringhini, Mr. Sante
Palsson, Miss. Stina Viola
Meyer, Mrs. Edgar Joseph (Leila Saks)
Landergren, Miss. Aurora Adelia
Widener, Mr. Harry Elkins
Betros, Mr. Tannous
Gustafsson, Mr. Karl Gideon
Bidois, Miss. Rosalie
Nakid, Miss. Maria ("Mary")
Tikkanen, Mr. Juho
Holverson, Mrs. Alexander Oskar (Mary Aline Towner)
Plotcharsky, Mr. Vasil
Davies, Mr. Charles Henry
Goodwin, Master. Sidney Leonard
Buss, Miss. Kate
Sadlier, Mr. Matthew
Lehmann, Miss. Bertha
Carter, Mr. William Ernest
Jansson, Mr. Carl Olof
Gustafsson, Mr. Johan Birger
Newell, Miss. Marjorie
Sandstrom, Mrs. Hjalmar (Agnes Charlotta Bengtsson)
Johansson, Mr. Erik
Olsson, Miss. Elina
McKane, Mr. Peter David
Pain, Dr. Alfred
Trout, Mrs. William H (Jessie L)
Niskanen, Mr. Juha
Adams, Mr. John
Jussila, Miss. Mari Aina
Hakkarainen, Mr. Pekka Pietari
Oreskovic, Miss. Marija
Gale, Mr. Shadrach
Widegren, Mr. Carl/Charles Peter
Richards, Master. William Rowe
Birkeland, Mr. Hans Martin Monsen
Lefebre, Miss. Ida
Sdycoff, Mr. Todor
Hart, Mr. Henry
Minahan, Miss. Daisy E
Cunningham, Mr. Alfred Fleming
Sundman, Mr. Johan Julian
Meek, Mrs. Thomas (Annie Louise Rowley)
Drew, Mrs. James Vivian (Lulu Thorne Christian)
Silven, Miss. Lyyli Karoliina
Matthews, Mr. William John
Van Impe, Miss. Catharina
Gheorgheff, Mr. Stanio
Charters, Mr. David
Zimmerman, Mr. Leo
Danbom, Mrs. Ernst Gilbert (Anna Sigrid Maria Brogren)
Rosblom, Mr. Viktor Richard
Wiseman, Mr. Phillippe
Clarke, Mrs. Charles V (Ada Maria Winfield)
Phillips, Miss. Kate Florence ("Mrs Kate Louise Phillips Marshall")
Flynn, Mr. James
Pickard, Mr. Berk (Berk Trembisky)
Bjornstrom-Steffansson, Mr. Mauritz Hakan
Thorneycroft, Mrs. Percival (Florence Kate White)
Louch, Mrs. Charles Alexander (Alice Adelaide Slow)
Kallio, Mr. Nikolai Erland
Silvey, Mr. William Baird
Carter, Miss. Lucile Polk
Ford, Miss. Doolina Margaret "Daisy"
Richards, Mrs. Sidney (Emily Hocking)
Fortune, Mr. Mark
Kvillner, Mr. Johan Henrik Johannesson
Hart, Mrs. Benjamin (Esther Ada Bloomfield)
Hampe, Mr. Leon
Petterson, Mr. Johan Emil
Reynaldo, Ms. Encarnacion
Johannesen-Bratthammer, Mr. Bernt
Dodge, Master. Washington
Mellinger, Miss. Madeleine Violet
Seward, Mr. Frederic Kimber
Baclini, Miss. Marie Catherine
Peuchen, Major. Arthur Godfrey
West, Mr. Edwy Arthur
Hagland, Mr. Ingvald Olai Olsen
Foreman, Mr. Benjamin Laventall
Goldenberg, Mr. Samuel L
Peduzzi, Mr. Joseph
Jalsevac, Mr. Ivan
Millet, Mr. Francis Davis
Kenyon, Mrs. Frederick R (Marion)
Toomey, Miss. Ellen
O'Connor, Mr. Maurice
Anderson, Mr. Harry
Morley, Mr. William
Gee, Mr. Arthur H
Milling, Mr. Jacob Christian
Maisner, Mr. Simon
Goncalves, Mr. Manuel Estanslas
Campbell, Mr. William
Smart, Mr. John Montgomery
Scanlan, Mr. James
Baclini, Miss. Helene Barbara
Keefe, Mr. Arthur
Cacic, Mr. Luka
West, Mrs. Edwy Arthur (Ada Mary Worth)
Jerwan, Mrs. Amin S (Marie Marthe Thuillard)
Strandberg, Miss. Ida Sofia
Clifford, Mr. George Quincy
Renouf, Mr. Peter Henry
Braund, Mr. Lewis Richard
Karlsson, Mr. Nils August
Hirvonen, Miss. Hildur E
Goodwin, Master. Harold Victor
Frost, Mr. Anthony Wood "Archie"
Rouse, Mr. Richard Henry
Turkula, Mrs. (Hedwig)
Bishop, Mr. Dickinson H
Lefebre, Miss. Jeannie
Hoyt, Mrs. Frederick Maxfield (Jane Anne Forby)
Kent, Mr. Edward Austin
Somerton, Mr. Francis William
Coutts, Master. Eden Leslie "Neville"
Hagland, Mr. Konrad Mathias Reiersen
Windelov, Mr. Einar
Molson, Mr. Harry Markland
Artagaveytia, Mr. Ramon
Stanley, Mr. Edward Roland
Yousseff, Mr. Gerious
Eustis, Miss. Elizabeth Mussey
Shellard, Mr. Frederick William
Allison, Mrs. Hudson J C (Bessie Waldo Daniels)
Svensson, Mr. Olof
Calic, Mr. Petar
Canavan, Miss. Mary
O'Sullivan, Miss. Bridget Mary
Laitinen, Miss. Kristina Sofia
Maioni, Miss. Roberta
Penasco y Castellana, Mr. Victor de Satode
Quick, Mrs. Frederick Charles (Jane Richards)
Bradley, Mr. George ("George Arthur Brayton")
Olsen, Mr. Henry Margido
Lang, Mr. Fang
Daly, Mr. Eugene Patrick
Webber, Mr. James
McGough, Mr. James Robert
Rothschild, Mrs. Martin (Elizabeth L. Barrett)
Coleff, Mr. Satio
Walker, Mr. William Anderson
Lemore, Mrs. (Amelia Milley)
Ryan, Mr. Patrick
Angle, Mrs. William A (Florence "Mary" Agnes Hughes)
Pavlovic, Mr. Stefo
Perreault, Miss. Anne
Vovk, Mr. Janko
Lahoud, Mr. Sarkis
Hippach, Mrs. Louis Albert (Ida Sophia Fischer)
Kassem, Mr. Fared
Farrell, Mr. James
Ridsdale, Miss. Lucy
Farthing, Mr. John
Salonen, Mr. Johan Werner
Hocking, Mr. Richard George
Quick, Miss. Phyllis May
Toufik, Mr. Nakli
Elias, Mr. Joseph Jr
Peter, Mrs. Catherine (Catherine Rizk)
Cacic, Miss. Marija
Hart, Miss. Eva Miriam
Butt, Major. Archibald Willingham
LeRoy, Miss. Bertha
Risien, Mr. Samuel Beard
Frolicher, Miss. Hedwig Margaritha
Crosby, Miss. Harriet R
Andersson, Miss. Ingeborg Constanzia
Andersson, Miss. Sigrid Elisabeth
Beane, Mr. Edward
Douglas, Mr. Walter Donald
Nicholson, Mr. Arthur Ernest
Beane, Mrs. Edward (Ethel Clarke)
Padro y Manent, Mr. Julian
Goldsmith, Mr. Frank John
Davies, Master. John Morgan Jr
Thayer, Mr. John Borland Jr
Sharp, Mr. Percival James R
O'Brien, Mr. Timothy
Leeni, Mr. Fahim ("Philip Zenni")
Ohman, Miss. Velin
Wright, Mr. George
Duff Gordon, Lady. (Lucille Christiana Sutherland) ("Mrs Morgan")
Robbins, Mr. Victor
Taussig, Mrs. Emil (Tillie Mandelbaum)
de Messemaeker, Mrs. Guillaume Joseph (Emma)
Morrow, Mr. Thomas Rowan
Sivic, Mr. Husein
Norman, Mr. Robert Douglas
Simmons, Mr. John
Meanwell, Miss. (Marion Ogden)
Davies, Mr. Alfred J
Stoytcheff, Mr. Ilia
Palsson, Mrs. Nils (Alma Cornelia Berglund)
Doharr, Mr. Tannous
Jonsson, Mr. Carl
Harris, Mr. George
Appleton, Mrs. Edward Dale (Charlotte Lamson)
Flynn, Mr. John Irwin ("Irving")
Kelly, Miss. Mary
Rush, Mr. Alfred George John
Patchett, Mr. George
Garside, Miss. Ethel
Silvey, Mrs. William Baird (Alice Munger)
Caram, Mrs. Joseph (Maria Elias)
Jussila, Mr. Eiriik
Christy, Miss. Julie Rachel
Thayer, Mrs. John Borland (Marian Longstreth Morris)
Downton, Mr. William James
Ross, Mr. John Hugo
Paulner, Mr. Uscher
Taussig, Miss. Ruth
Jarvis, Mr. John Denzil
Frolicher-Stehli, Mr. Maxmillian
Gilinski, Mr. Eliezer
Murdlin, Mr. Joseph
Rintamaki, Mr. Matti
Stephenson, Mrs. Walter Bertram (Martha Eustis)
Elsbury, Mr. William James
Bourke, Miss. Mary
Chapman, Mr. John Henry
Van Impe, Mr. Jean Baptiste
Leitch, Miss. Jessie Wills
Johnson, Mr. Alfred
Boulos, Mr. Hanna
Duff Gordon, Sir. Cosmo Edmund ("Mr Morgan")
Jacobsohn, Mrs. Sidney Samuel (Amy Frances Christy)
Slabenoff, Mr. Petco
Harrington, Mr. Charles H
Torber, Mr. Ernst William
Homer, Mr. Harry ("Mr E Haven")
Lindell, Mr. Edvard Bengtsson
Karaic, Mr. Milan
Daniel, Mr. Robert Williams
Laroche, Mrs. Joseph (Juliette Marie Louise Lafargue)
Shutes, Miss. Elizabeth W
Andersson, Mrs. Anders Johan (Alfrida Konstantia Brogren)
Jardin, Mr. Jose Neto
Murphy, Miss. Margaret Jane
Horgan, Mr. John
Brocklebank, Mr. William Alfred
Herman, Miss. Alice
Danbom, Mr. Ernst Gilbert
Lobb, Mrs. William Arthur (Cordelia K Stanlick)
Becker, Miss. Marion Louise
Gavey, Mr. Lawrence
Yasbeck, Mr. Antoni
Kimball, Mr. Edwin Nelson Jr
Nakid, Mr. Sahid
Hansen, Mr. Henry Damsgaard
Bowen, Mr. David John "Dai"
Sutton, Mr. Frederick
Kirkland, Rev. Charles Leonard
Longley, Miss. Gretchen Fiske
Bostandyeff, Mr. Guentcho
O'Connell, Mr. Patrick D
Barkworth, Mr. Algernon Henry Wilson
Lundahl, Mr. Johan Svensson
Stahelin-Maeglin, Dr. Max
Parr, Mr. William Henry Marsh
Skoog, Miss. Mabel
Davis, Miss. Mary
Leinonen, Mr. Antti Gustaf
Collyer, Mr. Harvey
Panula, Mrs. Juha (Maria Emilia Ojala)
Thorneycroft, Mr. Percival
Jensen, Mr. Hans Peder
Sagesser, Mlle. Emma
Skoog, Miss. Margit Elizabeth
Foo, Mr. Choong
Baclini, Miss. Eugenie
Harper, Mr. Henry Sleeper
Cor, Mr. Liudevit
Simonius-Blumer, Col. Oberst Alfons
Willey, Mr. Edward
Stanley, Miss. Amy Zillah Elsie
Mitkoff, Mr. Mito
Doling, Miss. Elsie
Kalvik, Mr. Johannes Halvorsen
O'Leary, Miss. Hanora "Norah"
Hegarty, Miss. Hanora "Nora"
Hickman, Mr. Leonard Mark
Radeff, Mr. Alexander
Bourke, Mrs. John (Catherine)
Eitemiller, Mr. George Floyd
Newell, Mr. Arthur Webster
Frauenthal, Dr. Henry William
Badt, Mr. Mohamed
Colley, Mr. Edward Pomeroy
Coleff, Mr. Peju
Lindqvist, Mr. Eino William
Hickman, Mr. Lewis
Butler, Mr. Reginald Fenton
Rommetvedt, Mr. Knud Paust
Cook, Mr. Jacob
Taylor, Mrs. Elmer Zebley (Juliet Cummins Wright)
Brown, Mrs. Thomas William Solomon (Elizabeth Catherine Ford)
Davidson, Mr. Thornton
Mitchell, Mr. Henry Michael
Wilhelms, Mr. Charles
Watson, Mr. Ennis Hastings
Edvardsson, Mr. Gustaf Hjalmar
Sawyer, Mr. Frederick Charles
Turja, Miss. Anna Sofia
Goodwin, Mrs. Frederick (Augusta Tyler)
Cardeza, Mr. Thomas Drake Martinez
Peters, Miss. Katie
Hassab, Mr. Hammad
Olsvigen, Mr. Thor Anderson
Goodwin, Mr. Charles Edward
Brown, Mr. Thomas William Solomon
Laroche, Mr. Joseph Philippe Lemercier
Panula, Mr. Jaako Arnold
Dakic, Mr. Branko
Fischer, Mr. Eberhard Thelander
Madill, Miss. Georgette Alexandra
Dick, Mr. Albert Adrian
Karun, Miss. Manca
Lam, Mr. Ali
Saad, Mr. Khalil
Weir, Col. John
Chapman, Mr. Charles Henry
Kelly, Mr. James
Mullens, Miss. Katherine "Katie"
Thayer, Mr. John Borland
Humblen, Mr. Adolf Mathias Nicolai Olsen
Astor, Mrs. John Jacob (Madeleine Talmadge Force)
Silverthorne, Mr. Spencer Victor
Barbara, Miss. Saiide
Gallagher, Mr. Martin
Hansen, Mr. Henrik Juul
Morley, Mr. Henry Samuel ("Mr Henry Marshall")
Kelly, Mrs. Florence "Fannie"
Calderhead, Mr. Edward Pennington
Cleaver, Miss. Alice
Moubarek, Master. Halim Gonios ("William George")
Mayne, Mlle. Berthe Antonine ("Mrs de Villiers")
Klaber, Mr. Herman
Taylor, Mr. Elmer Zebley
Larsson, Mr. August Viktor

In [17]:
for n in df.index:
    print(df.loc[n])

PassengerId            1
Survived               0
Pclass                 3
Sex                 male
Age                 22.0
SibSp                  1
Parch                  0
Ticket         A/5 21171
Fare                7.25
Cabin                NaN
Embarked               S
Name: Braund, Mr. Owen Harris, dtype: object
PassengerId           2
Survived              1
Pclass                1
Sex              female
Age                38.0
SibSp                 1
Parch                 0
Ticket         PC 17599
Fare            71.2833
Cabin               C85
Embarked              C
Name: Cumings, Mrs. John Bradley (Florence Briggs Thayer), dtype: object
PassengerId                   3
Survived                      1
Pclass                        3
Sex                      female
Age                        26.0
SibSp                         0
Parch                         0
Ticket         STON/O2. 3101282
Fare                      7.925
Cabin                       NaN
Embarked                      S
Name: Heikkinen, Miss. Laina, dtype: object
PassengerId         4
Survived            1
Pclass              1
Sex            female
Age              35.0
SibSp               1
Parch               0
Ticket         113803
Fare             53.1
Cabin            C123
Embarked            S
Name: Futrelle, Mrs. Jacques Heath (Lily May Peel), dtype: object
PassengerId         5
Survived            0
Pclass              3
Sex              male
Age              35.0
SibSp               0
Parch               0
Ticket         373450
Fare             8.05
Cabin             NaN
Embarked            S
Name: Allen, Mr. William Henry, dtype: object
PassengerId         6
Survived            0
Pclass              3
Sex              male
Age               NaN
SibSp               0
Parch               0
Ticket         330877
Fare           8.4583
Cabin             NaN
Embarked            Q
Name: Moran, Mr. James, dtype: object
PassengerId          7
Survived             0
Pclass               1
Sex               male
Age               54.0
SibSp                0
Parch                0
Ticket           17463
Fare           51.8625
Cabin              E46
Embarked             S
Name: McCarthy, Mr. Timothy J, dtype: object
PassengerId         8
Survived            0
Pclass              3
Sex              male
Age               2.0
SibSp               3
Parch               1
Ticket         349909
Fare           21.075
Cabin             NaN
Embarked            S
Name: Palsson, Master. Gosta Leonard, dtype: object
PassengerId          9
Survived             1
Pclass               3
Sex             female
Age               27.0
SibSp                0
Parch                2
Ticket          347742
Fare           11.1333
Cabin              NaN
Embarked             S
Name: Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg), dtype: object
PassengerId         10
Survived             1
Pclass               2
Sex             female
Age               14.0
SibSp                1
Parch                0
Ticket          237736
Fare           30.0708
Cabin              NaN
Embarked             C
Name: Nasser, Mrs. Nicholas (Adele Achem), dtype: object
PassengerId         11
Survived             1
Pclass               3
Sex             female
Age                4.0
SibSp                1
Parch                1
Ticket         PP 9549
Fare              16.7
Cabin               G6
Embarked             S
Name: Sandstrom, Miss. Marguerite Rut, dtype: object
PassengerId        12
Survived            1
Pclass              1
Sex            female
Age              58.0
SibSp               0
Parch               0
Ticket         113783
Fare            26.55
Cabin            C103
Embarked            S
Name: Bonnell, Miss. Elizabeth, dtype: object
PassengerId           13
Survived               0
Pclass                 3
Sex                 male
Age                 20.0
SibSp                  0
Parch                  0
Ticket         A/5. 2151
Fare                8.05
Cabin                NaN
Embarked               S
Name: Saundercock, Mr. William Henry, dtype: object
PassengerId        14
Survived            0
Pclass              3
Sex              male
Age              39.0
SibSp               1
Parch               5
Ticket         347082
Fare           31.275
Cabin             NaN
Embarked            S
Name: Andersson, Mr. Anders Johan, dtype: object
PassengerId        15
Survived            0
Pclass              3
Sex            female
Age              14.0
SibSp               0
Parch               0
Ticket         350406
Fare           7.8542
Cabin             NaN
Embarked            S
Name: Vestrom, Miss. Hulda Amanda Adolfina, dtype: object
PassengerId        16
Survived            1
Pclass              2
Sex            female
Age              55.0
SibSp               0
Parch               0
Ticket         248706
Fare             16.0
Cabin             NaN
Embarked            S
Name: Hewlett, Mrs. (Mary D Kingcome) , dtype: object
PassengerId        17
Survived            0
Pclass              3
Sex              male
Age               2.0
SibSp               4
Parch               1
Ticket         382652
Fare           29.125
Cabin             NaN
Embarked            Q
Name: Rice, Master. Eugene, dtype: object
PassengerId        18
Survived            1
Pclass              2
Sex              male
Age               NaN
SibSp               0
Parch               0
Ticket         244373
Fare             13.0
Cabin             NaN
Embarked            S
Name: Williams, Mr. Charles Eugene, dtype: object
PassengerId        19
Survived            0
Pclass              3
Sex            female
Age              31.0
SibSp               1
Parch               0
Ticket         345763
Fare             18.0
Cabin             NaN
Embarked            S
Name: Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele), dtype: object
PassengerId        20
Survived            1
Pclass              3
Sex            female
Age               NaN
SibSp               0
Parch               0
Ticket           2649
Fare            7.225
Cabin             NaN
Embarked            C
Name: Masselmani, Mrs. Fatima, dtype: object
PassengerId        21
Survived            0
Pclass              2
Sex              male
Age              35.0
SibSp               0
Parch               0
Ticket         239865
Fare             26.0
Cabin             NaN
Embarked            S
Name: Fynney, Mr. Joseph J, dtype: object
PassengerId        22
Survived            1
Pclass              2
Sex              male
Age              34.0
SibSp               0
Parch               0
Ticket         248698
Fare             13.0
Cabin             D56
Embarked            S
Name: Beesley, Mr. Lawrence, dtype: object
PassengerId        23
Survived            1
Pclass              3
Sex            female
Age              15.0
SibSp               0
Parch               0
Ticket         330923
Fare           8.0292
Cabin             NaN
Embarked            Q
Name: McGowan, Miss. Anna "Annie", dtype: object
PassengerId        24
Survived            1
Pclass              1
Sex              male
Age              28.0
SibSp               0
Parch               0
Ticket         113788
Fare             35.5
Cabin              A6
Embarked            S
Name: Sloper, Mr. William Thompson, dtype: object
PassengerId        25
Survived            0
Pclass              3
Sex            female
Age               8.0
SibSp               3
Parch               1
Ticket         349909
Fare           21.075
Cabin             NaN
Embarked            S
Name: Palsson, Miss. Torborg Danira, dtype: object
PassengerId         26
Survived             1
Pclass               3
Sex             female
Age               38.0
SibSp                1
Parch                5
Ticket          347077
Fare           31.3875
Cabin              NaN
Embarked             S
Name: Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson), dtype: object
PassengerId       27
Survived           0
Pclass             3
Sex             male
Age              NaN
SibSp              0
Parch              0
Ticket          2631
Fare           7.225
Cabin            NaN
Embarked           C
Name: Emir, Mr. Farred Chehab, dtype: object
PassengerId             28
Survived                 0
Pclass                   1
Sex                   male
Age                   19.0
SibSp                    3
Parch                    2
Ticket               19950
Fare                 263.0
Cabin          C23 C25 C27
Embarked                 S
Name: Fortune, Mr. Charles Alexander, dtype: object
PassengerId        29
Survived            1
Pclass              3
Sex            female
Age               NaN
SibSp               0
Parch               0
Ticket         330959
Fare           7.8792
Cabin             NaN
Embarked            Q
Name: O'Dwyer, Miss. Ellen "Nellie", dtype: object
PassengerId        30
Survived            0
Pclass              3
Sex              male
Age               NaN
SibSp               0
Parch               0
Ticket         349216
Fare           7.8958
Cabin             NaN
Embarked            S
Name: Todoroff, Mr. Lalio, dtype: object
PassengerId          31
Survived              0
Pclass                1
Sex                male
Age                40.0
SibSp                 0
Parch                 0
Ticket         PC 17601
Fare            27.7208
Cabin               NaN
Embarked              C
Name: Uruchurtu, Don. Manuel E, dtype: object
PassengerId          32
Survived              1
Pclass                1
Sex              female
Age                 NaN
SibSp                 1
Parch                 0
Ticket         PC 17569
Fare           146.5208
Cabin               B78
Embarked              C
Name: Spencer, Mrs. William Augustus (Marie Eugenie), dtype: object
PassengerId        33
Survived            1
Pclass              3
Sex            female
Age               NaN
SibSp               0
Parch               0
Ticket         335677
Fare             7.75
Cabin             NaN
Embarked            Q
Name: Glynn, Miss. Mary Agatha, dtype: object
PassengerId            34
Survived                0
Pclass                  2
Sex                  male
Age                  66.0
SibSp                   0
Parch                   0
Ticket         C.A. 24579
Fare                 10.5
Cabin                 NaN
Embarked                S
Name: Wheadon, Mr. Edward H, dtype: object
PassengerId          35
Survived              0
Pclass                1
Sex                male
Age                28.0
SibSp                 1
Parch                 0
Ticket         PC 17604
Fare            82.1708
Cabin               NaN
Embarked              C
Name: Meyer, Mr. Edgar Joseph, dtype: object
PassengerId        36
Survived            0
Pclass              1
Sex              male
Age              42.0
SibSp               1
Parch               0
Ticket         113789
Fare             52.0
Cabin             NaN
Embarked            S
Name: Holverson, Mr. Alexander Oskar, dtype: object
PassengerId        37
Survived            1
Pclass              3
Sex              male
Age               NaN
SibSp               0
Parch               0
Ticket           2677
Fare           7.2292
Cabin             NaN
Embarked            C
Name: Mamee, Mr. Hanna, dtype: object
PassengerId            38
Survived                0
Pclass                  3
Sex                  male
Age                  21.0
SibSp                   0
Parch                   0
Ticket         A./5. 2152
Fare                 8.05
Cabin                 NaN
Embarked                S
Name: Cann, Mr. Ernest Charles, dtype: object
PassengerId        39
Survived            0
Pclass              3
Sex            female
Age              18.0
SibSp               2
Parch               0
Ticket         345764
Fare             18.0
Cabin             NaN
Embarked            S
Name: Vander Planke, Miss. Augusta Maria, dtype: object
PassengerId         40
Survived             1
Pclass               3
Sex             female
Age               14.0
SibSp                1
Parch                0
Ticket            2651
Fare           11.2417
Cabin              NaN
Embarked             C
Name: Nicola-Yarred, Miss. Jamila, dtype: object
PassengerId        41
Survived            0
Pclass              3
Sex            female
Age              40.0
SibSp               1
Parch               0
Ticket           7546
Fare            9.475
Cabin             NaN
Embarked            S
Name: Ahlin, Mrs. Johan (Johanna Persdotter Larsson), dtype: object
PassengerId        42
Survived            0
Pclass              2
Sex            female
Age              27.0
SibSp               1
Parch               0
Ticket          11668
Fare             21.0
Cabin             NaN
Embarked            S
Name: Turpin, Mrs. William John Robert (Dorothy Ann Wonnacott), dtype: object
PassengerId        43
Survived            0
Pclass              3
Sex              male
Age               NaN
SibSp               0
Parch               0
Ticket         349253
Fare           7.8958
Cabin             NaN
Embarked            C
Name: Kraeff, Mr. Theodor, dtype: object
PassengerId               44
Survived                   1
Pclass                     2
Sex                   female
Age                      3.0
SibSp                      1
Parch                      2
Ticket         SC/Paris 2123
Fare                 41.5792
Cabin                    NaN
Embarked                   C
Name: Laroche, Miss. Simonne Marie Anne Andree, dtype: object
PassengerId        45
Survived            1
Pclass              3
Sex            female
Age              19.0
SibSp               0
Parch               0
Ticket         330958
Fare           7.8792
Cabin             NaN
Embarked            Q
Name: Devaney, Miss. Margaret Delia, dtype: object
PassengerId                 46
Survived                     0
Pclass                       3
Sex                       male
Age                        NaN
SibSp                        0
Parch                        0
Ticket         S.C./A.4. 23567
Fare                      8.05
Cabin                      NaN
Embarked                     S
Name: Rogers, Mr. William John, dtype: object
PassengerId        47
Survived            0
Pclass              3
Sex              male
Age               NaN
SibSp               1
Parch               0
Ticket         370371
Fare             15.5
Cabin             NaN
Embarked            Q
Name: Lennon, Mr. Denis, dtype: object
PassengerId        48
Survived            1
Pclass              3
Sex            female
Age               NaN
SibSp               0
Parch               0
Ticket          14311
Fare             7.75
Cabin             NaN
Embarked            Q
Name: O'Driscoll, Miss. Bridget, dtype: object
PassengerId         49
Survived             0
Pclass               3
Sex               male
Age                NaN
SibSp                2
Parch                0
Ticket            2662
Fare           21.6792
Cabin              NaN
Embarked             C
Name: Samaan, Mr. Youssef, dtype: object
PassengerId        50
Survived            0
Pclass              3
Sex            female
Age              18.0
SibSp               1
Parch               0
Ticket         349237
Fare             17.8
Cabin             NaN
Embarked            S
Name: Arnold-Franchi, Mrs. Josef (Josefine Franchi), dtype: object
PassengerId         51
Survived             0
Pclass               3
Sex               male
Age                7.0
SibSp                4
Parch                1
Ticket         3101295
Fare           39.6875
Cabin              NaN
Embarked             S
Name: Panula, Master. Juha Niilo, dtype: object
PassengerId            52
Survived                0
Pclass                  3
Sex                  male
Age                  21.0
SibSp                   0
Parch                   0
Ticket         A/4. 39886
Fare                  7.8
Cabin                 NaN
Embarked                S
Name: Nosworthy, Mr. Richard Cater, dtype: object
PassengerId          53
Survived              1
Pclass                1
Sex              female
Age                49.0
SibSp                 1
Parch                 0
Ticket         PC 17572
Fare            76.7292
Cabin               D33
Embarked              C
Name: Harper, Mrs. Henry Sleeper (Myna Haxtun), dtype: object
PassengerId        54
Survived            1
Pclass              2
Sex            female
Age              29.0
SibSp               1
Parch               0
Ticket           2926
Fare             26.0
Cabin             NaN
Embarked            S
Name: Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkinson), dtype: object
PassengerId         55
Survived             0
Pclass               1
Sex               male
Age               65.0
SibSp                0
Parch                1
Ticket          113509
Fare           61.9792
Cabin              B30
Embarked             C
Name: Ostby, Mr. Engelhart Cornelius, dtype: object
PassengerId       56
Survived           1
Pclass             1
Sex             male
Age              NaN
SibSp              0
Parch              0
Ticket         19947
Fare            35.5
Cabin            C52
Embarked           S
Name: Woolner, Mr. Hugh, dtype: object
PassengerId            57
Survived                1
Pclass                  2
Sex                female
Age                  21.0
SibSp                   0
Parch                   0
Ticket         C.A. 31026
Fare                 10.5
Cabin                 NaN
Embarked                S
Name: Rugg, Miss. Emily, dtype: object
PassengerId        58
Survived            0
Pclass              3
Sex              male
Age              28.5
SibSp               0
Parch               0
Ticket           2697
Fare           7.2292
Cabin             NaN
Embarked            C
Name: Novel, Mr. Mansouer, dtype: object
PassengerId            59
Survived                1
Pclass                  2
Sex                female
Age                   5.0
SibSp                   1
Parch                   2
Ticket         C.A. 34651
Fare                27.75
Cabin                 NaN
Embarked                S
Name: West, Miss. Constance Mirium, dtype: object
PassengerId         60
Survived             0
Pclass               3
Sex               male
Age               11.0
SibSp                5
Parch                2
Ticket         CA 2144
Fare              46.9
Cabin              NaN
Embarked             S
Name: Goodwin, Master. William Frederick, dtype: object
PassengerId        61
Survived            0
Pclass              3
Sex              male
Age              22.0
SibSp               0
Parch               0
Ticket           2669
Fare           7.2292
Cabin             NaN
Embarked            C
Name: Sirayanian, Mr. Orsen, dtype: object
PassengerId        62
Survived            1
Pclass              1
Sex            female
Age              38.0
SibSp               0
Parch               0
Ticket         113572
Fare             80.0
Cabin             B28
Embarked          NaN
Name: Icard, Miss. Amelie, dtype: object
PassengerId        63
Survived            0
Pclass              1
Sex              male
Age              45.0
SibSp               1
Parch               0
Ticket          36973
Fare           83.475
Cabin             C83
Embarked            S
Name: Harris, Mr. Henry Birkhardt, dtype: object
PassengerId        64
Survived            0
Pclass              3
Sex              male
Age               4.0
SibSp               3
Parch               2
Ticket         347088
Fare             27.9
Cabin             NaN
Embarked            S
Name: Skoog, Master. Harald, dtype: object
PassengerId          65
Survived              0
Pclass                1
Sex                male
Age                 NaN
SibSp                 0
Parch                 0
Ticket         PC 17605
Fare            27.7208
Cabin               NaN
Embarked              C
Name: Stewart, Mr. Albert A, dtype: object
PassengerId         66
Survived             1
Pclass               3
Sex               male